server:
  port: 9002

spring:
  application:
    name: USER-SERVICE

  eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://localhost:8761/eureka/
      instance:
        hostname: localhost

#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 500
#        readTimeout: 1500



